prophet:
  changepoint_prior_scale: [0.01, 0.05, 0.1, 0.5]
  seasonality_prior_scale: [1.0, 5.0, 10.0, 20.0]
  seasonality_mode: "multiplicative"
  yearly_seasonality: true
  initial: "730 days"
  period: "180 days"
  horizon: "180 days"
